# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd28534321cb8aa14374c203bc04a65ac0a450c5f16ff6dc302e963c7a18356e148def5c3dbf9f8852d165fbc4a825e32ce5fa10255dd5389345a9b1e4479f7

test:
  secret_key_base: ebfdd65d45c2e0d368f294aafe93936f340ce6ec8e17f22ff00fa7717276679bfc72cfb7ab9d07ae0af8c6b87bfd45d692ddf55baa07081fe4134c867749c8a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
